name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests (headless)
        run: |
          # Use headless mode for JavaFX
          export JAVA_TOOL_OPTIONS="-Djava.awt.headless=true"
          mvn -B clean test --file pom.xml

      - name: Generate Jacoco coverage report
        run: mvn jacoco:report --file pom.xml
